use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // GENERATED BY DEFAULT AS IDENTITY は既存行を挿入順に自動採番でバックフィルするため、
        // created_at (同一集計サイクル内で全行同値になり得る) に代わるタイブレークフリーな
        // カーソルとして使える。
        manager
            .get_connection()
            .execute_unprepared(
                "ALTER TABLE news_strategy_link ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
            )
            .await?;

        manager
            .get_connection()
            .execute_unprepared(
                "CREATE INDEX news_strategy_link_seq_idx ON news_strategy_link (strategy_id, seq)",
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .get_connection()
            .execute_unprepared("DROP INDEX news_strategy_link_seq_idx")
            .await?;

        manager
            .get_connection()
            .execute_unprepared("ALTER TABLE news_strategy_link DROP COLUMN seq")
            .await?;

        Ok(())
    }
}
