use sea_orm_migration::prelude::*;

pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20260925_075026_drop_news_strategy_link"
    }
}

#[derive(DeriveIden)]
enum NewsStrategyLink {
    Table,
    NewsId,
    StrategyId,
    RefKind,
    RefId,
    MatchedTerm,
    CreatedAt,
}

#[derive(DeriveIden)]
enum NewsItem {
    Table,
    Id,
}

#[derive(DeriveIden)]
enum Strategy {
    Table,
    Id,
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(NewsStrategyLink::Table).to_owned())
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(NewsStrategyLink::Table)
                    .col(ColumnDef::new(NewsStrategyLink::NewsId).uuid().not_null())
                    .col(
                        ColumnDef::new(NewsStrategyLink::StrategyId)
                            .uuid()
                            .not_null(),
                    )
                    .col(ColumnDef::new(NewsStrategyLink::RefKind).text().not_null())
                    .col(ColumnDef::new(NewsStrategyLink::RefId).text().not_null())
                    .col(
                        ColumnDef::new(NewsStrategyLink::MatchedTerm)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(NewsStrategyLink::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .primary_key(
                        Index::create()
                            .col(NewsStrategyLink::NewsId)
                            .col(NewsStrategyLink::StrategyId)
                            .col(NewsStrategyLink::RefKind)
                            .col(NewsStrategyLink::RefId),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(NewsStrategyLink::Table, NewsStrategyLink::NewsId)
                            .to(NewsItem::Table, NewsItem::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(NewsStrategyLink::Table, NewsStrategyLink::StrategyId)
                            .to(Strategy::Table, Strategy::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        let connection = manager.get_connection();
        connection
            .execute_unprepared(
                "ALTER TABLE news_strategy_link \
                 ADD CONSTRAINT news_strategy_link_ref_kind_check \
                 CHECK (ref_kind IN ('stock', 'indicator', 'sector', 'theme'))",
            )
            .await?;
        connection
            .execute_unprepared(
                "CREATE INDEX news_strategy_link_strategy_idx \
                 ON news_strategy_link (strategy_id, news_id)",
            )
            .await?;
        connection
            .execute_unprepared(
                "ALTER TABLE news_strategy_link \
                 ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
            )
            .await?;
        connection
            .execute_unprepared(
                "CREATE INDEX news_strategy_link_seq_idx \
                 ON news_strategy_link (strategy_id, seq)",
            )
            .await?;

        Ok(())
    }
}
