use chrono::NaiveDate;

/// 銘柄ごとの開示時点の財務情報。
#[derive(Debug, Clone, PartialEq)]
pub struct FinancialSummary {
    pub code: String,
    pub disclosure_no: String,
    pub disclosure_date: NaiveDate,
    /// 開示種別と対象期間で報告グループを識別する不透明なキー。
    pub report_group_key: String,
    pub document_type: Option<String>,
    pub current_period_type: Option<String>,
    pub current_period_start: Option<NaiveDate>,
    pub current_period_end: Option<NaiveDate>,
    pub current_fiscal_year_start: Option<NaiveDate>,
    pub current_fiscal_year_end: Option<NaiveDate>,
    pub sales: Option<f64>,
    pub operating_profit: Option<f64>,
    pub ordinary_profit: Option<f64>,
    pub net_profit: Option<f64>,
    pub eps: Option<f64>,
    pub bps: Option<f64>,
    pub total_assets: Option<f64>,
    pub equity: Option<f64>,
    pub equity_to_asset_ratio: Option<f64>,
    pub roe: Option<f64>,
    pub cash_flow_operating: Option<f64>,
    pub cash_flow_investing: Option<f64>,
    pub cash_flow_financing: Option<f64>,
    pub cash_and_equivalents: Option<f64>,
    pub dividend_annual: Option<f64>,
    pub dividend_annual_forecast: Option<f64>,
    pub dividend_annual_forecast_next: Option<f64>,
    pub forecast_sales: Option<f64>,
    pub forecast_operating_profit: Option<f64>,
    pub forecast_ordinary_profit: Option<f64>,
    pub forecast_net_profit: Option<f64>,
    pub forecast_eps: Option<f64>,
    pub next_forecast_sales: Option<f64>,
    pub next_forecast_operating_profit: Option<f64>,
    pub next_forecast_ordinary_profit: Option<f64>,
    pub next_forecast_net_profit: Option<f64>,
    pub next_forecast_eps: Option<f64>,
}
