//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "instruments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub market: String,
    pub sector: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bars::Entity")]
    Bars,
    #[sea_orm(has_many = "super::minute_bars::Entity")]
    MinuteBars,
}

impl Related<super::bars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bars.def()
    }
}

impl Related<super::minute_bars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MinuteBars.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
