//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "news_item_content")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub news_item_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::news_item::Entity",
        from = "Column::NewsItemId",
        to = "super::news_item::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NewsItem,
}

impl Related<super::news_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
