//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "note")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub kind: Option<String>,
    pub trigger: Option<String>,
    pub trigger_label: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub execution_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(
        belongs_to = "super::note_kind::Entity",
        from = "Column::Kind",
        to = "super::note_kind::Column::Key",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    NoteKind,
    #[sea_orm(has_many = "super::note_link::Entity")]
    NoteLink,
    #[sea_orm(has_many = "super::note_ref::Entity")]
    NoteRef,
    #[sea_orm(has_many = "super::note_version::Entity")]
    NoteVersion,
    #[sea_orm(has_many = "super::prediction::Entity")]
    Prediction,
    #[sea_orm(has_many = "super::trade_note::Entity")]
    TradeNote,
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotation.def()
    }
}

impl Related<super::note_kind::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteKind.def()
    }
}

impl Related<super::note_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteLink.def()
    }
}

impl Related<super::note_ref::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteRef.def()
    }
}

impl Related<super::note_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteVersion.def()
    }
}

impl Related<super::prediction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prediction.def()
    }
}

impl Related<super::trade_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TradeNote.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
