//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "paper_order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_id: Uuid,
    pub stock_id: String,
    #[sea_orm(column_type = "Text")]
    pub side: String,
    pub qty: i64,
    pub note_version_id: Uuid,
    pub ordered_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::note_version::Entity",
        from = "Column::NoteVersionId",
        to = "super::note_version::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NoteVersion,
    #[sea_orm(
        belongs_to = "super::paper_account::Entity",
        from = "Column::AccountId",
        to = "super::paper_account::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PaperAccount,
    #[sea_orm(has_one = "super::paper_order_result::Entity")]
    PaperOrderResult,
    #[sea_orm(
        belongs_to = "super::stock::Entity",
        from = "Column::StockId",
        to = "super::stock::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stock,
}

impl Related<super::note_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NoteVersion.def()
    }
}

impl Related<super::paper_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperAccount.def()
    }
}

impl Related<super::paper_order_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperOrderResult.def()
    }
}

impl Related<super::stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stock.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
