//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "paper_account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(unique_key = "uidx_paper_account_strategy_purpose")]
    pub strategy_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "uidx_paper_account_strategy_purpose"
    )]
    pub purpose: String,
    pub initial_cash_jpy: Decimal,
    pub benchmark_stock_id: Option<String>,
    pub started_on: Date,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agent_config::Entity",
        from = "Column::Purpose",
        to = "super::agent_config::Column::Purpose",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    AgentConfig,
    #[sea_orm(has_many = "super::paper_order::Entity")]
    PaperOrder,
    #[sea_orm(
        belongs_to = "super::stock::Entity",
        from = "Column::BenchmarkStockId",
        to = "super::stock::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stock,
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::agent_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentConfig.def()
    }
}

impl Related<super::paper_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperOrder.def()
    }
}

impl Related<super::stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stock.def()
    }
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
