//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_group_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub stock_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub group_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stock::Entity",
        from = "Column::StockId",
        to = "super::stock::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Stock,
    #[sea_orm(
        belongs_to = "super::stock_group::Entity",
        from = "Column::GroupId",
        to = "super::stock_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StockGroup,
}

impl Related<super::stock::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stock.def()
    }
}

impl Related<super::stock_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
