//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_stock_group_axis_id_key")]
    pub axis_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "idx_stock_group_axis_id_key")]
    pub key: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_axis::Entity",
        from = "Column::AxisId",
        to = "super::group_axis::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    GroupAxis,
    #[sea_orm(has_many = "super::stock_group_member::Entity")]
    StockGroupMember,
}

impl Related<super::group_axis::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupAxis.def()
    }
}

impl Related<super::stock_group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockGroupMember.def()
    }
}

impl Related<super::stock::Entity> for Entity {
    fn to() -> RelationDef {
        super::stock_group_member::Relation::Stock.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stock_group_member::Relation::StockGroup.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
