//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub market: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub product_category: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stock_group_member::Entity")]
    StockGroupMember,
}

impl Related<super::stock_group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockGroupMember.def()
    }
}

impl Related<super::stock_group::Entity> for Entity {
    fn to() -> RelationDef {
        super::stock_group_member::Relation::StockGroup.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stock_group_member::Relation::Stock.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
