//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "strategy")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::checkpoint::Entity")]
    Checkpoint,
    #[sea_orm(has_many = "super::custom_indicator::Entity")]
    CustomIndicator,
    #[sea_orm(has_many = "super::paper_account::Entity")]
    PaperAccount,
    #[sea_orm(has_many = "super::prediction::Entity")]
    Prediction,
    #[sea_orm(has_many = "super::strategy_earnings_target::Entity")]
    StrategyEarningsTarget,
    #[sea_orm(has_many = "super::strategy_investable_amount::Entity")]
    StrategyInvestableAmount,
    #[sea_orm(has_many = "super::strategy_task::Entity")]
    StrategyTask,
    #[sea_orm(has_many = "super::trade::Entity")]
    Trade,
    #[sea_orm(has_many = "super::trigger::Entity")]
    Trigger,
}

impl Related<super::checkpoint::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkpoint.def()
    }
}

impl Related<super::custom_indicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomIndicator.def()
    }
}

impl Related<super::paper_account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperAccount.def()
    }
}

impl Related<super::prediction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prediction.def()
    }
}

impl Related<super::strategy_earnings_target::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyEarningsTarget.def()
    }
}

impl Related<super::strategy_investable_amount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyInvestableAmount.def()
    }
}

impl Related<super::strategy_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyTask.def()
    }
}

impl Related<super::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

impl Related<super::trigger::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trigger.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
