scope/frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**
scope/backend:
  - changed-files:
      - any-glob-to-any-file: backend/**
scope/agent:
  - changed-files:
      - any-glob-to-any-file: agent/**
