# Changes here will be overwritten by Copier
_commit: v0.3.5-2-g40b7db3
_src_path: https://github.com/fohte/generic-boilerplate
description: 個人向け日本株投資プラットフォーム
is_public: false
project_name: t-rader
subpackages:
  - name: frontend
    type: node
  - name: backend
    type: rust
type: base
use_coverage: true
use_release_please: false
