# Changes here will be overwritten by Copier
_commit: v0.3.11
_src_path: https://github.com/fohte/generic-boilerplate
description: 個人向け日本株投資プラットフォーム
is_public: false
monorepo_node_workspace: false
node_package_manager: bun
project_name: t-rader
subpackages:
-   name: frontend
    type: node
-   name: backend
    type: rust
type: base
use_coverage: true
use_release_please: false
