# Changes here will be overwritten by Copier
_commit: v0.10.1
_src_path: https://github.com/fohte/generic-boilerplate
description: 個人向け日本株投資プラットフォーム
is_public: true
monorepo_node_workspace: true
project_name: t-rader
repo_language: ja
subpackages:
  - name: frontend
    spa: true
    type: node
  - name: backend
    type: rust
  - name: agent
    type: node
    web_app: true
type: base
use_coverage: true
use_release_please: false
