# Changes here will be overwritten by Copier
_commit: v0.8.2
_src_path: https://github.com/fohte/generic-boilerplate
description: 個人向け日本株投資プラットフォーム
is_public: true
project_name: t-rader
repo_language: ja
type: base
use_release_please: false
