import { config } from '@fohte/eslint-config'
import storybook from 'eslint-plugin-storybook'

export default config(
  {
    typescript: { typeChecked: true },
    errorHandling: {},
    tailwind: { cssConfigPath: 'frontend/src/index.css' },
  },
  ...storybook.configs['flat/recommended'],
  {
    // mockServiceWorker.js is generated by `msw init`; it must not be linted
    // or reformatted (see .prettierignore).
    ignores: ['**/mockServiceWorker.js'],
  },
  {
    // vite.config.ts/vitest.config.ts are loaded through Vite's own
    // esbuild-based config loader, which doesn't resolve the package.json
    // "imports" field, unlike the Rollup pipeline that bundles the app
    // itself. .storybook/vitest.setup*.ts import their siblings (e.g.
    // .storybook/preview.ts, .storybook/screenshot-viewport.ts) by relative
    // path because there's no "imports" alias for them: only src/ has a
    // generic "#*" pattern, while .storybook entries (e.g.
    // #storybook/story-router) are defined one file at a time.
    files: [
      'frontend/.storybook/vitest.setup*.ts',
      'frontend/vite.config.ts',
      'frontend/vitest.config.ts',
      'frontend/vitest.screenshot.config.ts',
    ],
    rules: { 'no-restricted-imports': 'off' },
  },
  // TanStack Router の自動生成ファイル
  { ignores: ['frontend/src/routeTree.gen.ts'] },
  // openapi-typescript の自動生成ファイル。OpenAPI スキーマの型導出の都合で
  // `null | unknown` のような lint 対象の型が現れることがあるが、手で直す対象ではない
  { ignores: ['**/schema.gen.d.ts'] },
  // projectService はプロセス内で一度だけ生成されるシングルトンのため、files を
  // frontend 配下に絞ると最初にパースされる ts ファイル (glob 順で frontend より前) が
  // 生成条件を決めてしまい allowDefaultProject が無視される。全 ts ファイルに適用する
  {
    files: ['**/*.ts{,x}'],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            'frontend/.storybook/main.ts',
            'frontend/.storybook/preview.ts',
            'frontend/.storybook/vitest.setup.ts',
            'frontend/.storybook/vitest.setup.screenshot.ts',
          ],
        },
      },
    },
  },
  {
    files: ['frontend/**/*.ts{,x}'],
    rules: {
      // TanStack Router/Query の型定義が any を返すケースがあるため無効化
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },
)
