[package]
name = "gateway-eoddata"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
chrono-tz = { workspace = true }
core-application = { workspace = true }
core-domain = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
indoc = "=2.0.7"
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = { workspace = true }

[lints]
workspace = true
