[env]
DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url backend dev') }}"
TEST_DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url backend test') }}"
_.file = ['.env', '.env.local']
