//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bars")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub instrument_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub timeframe: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub timestamp: DateTimeWithTimeZone,
    pub open: Decimal,
    pub high: Decimal,
    pub low: Decimal,
    pub close: Decimal,
    pub volume: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::instruments::Entity",
        from = "Column::InstrumentId",
        to = "super::instruments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instruments,
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instruments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
