//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "checkpoint")]
#[schema(as = Checkpoint)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "checkpoint_strategy_graph_stream_idx")]
    pub strategy_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "checkpoint_strategy_graph_stream_idx"
    )]
    pub graph: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "checkpoint_strategy_graph_stream_idx"
    )]
    pub stream: String,
    #[sea_orm(column_type = "Text")]
    pub cursor: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub updated_by_run_id: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
