//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "custom_indicator")]
#[schema(as = CustomIndicator)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub indicator_id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub scope: String,
    #[sea_orm(unique_key = "custom_indicator_strategy_name_idx")]
    pub strategy_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub input_schema: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub output_schema: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
