//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "edinet_large_volume_shareholdings")]
#[schema(as = EdinetLargeVolumeShareholdings)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub doc_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub code: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub edinet_code: String,
    pub sub_date: Date,
    #[sea_orm(column_type = "JsonBinary")]
    pub document: Json,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
