//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "financial_summary")]
#[schema(as = FinancialSummary)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub disclosure_no: String,
    pub disclosure_date: Date,
    pub report_group_key: String,
    pub document_type: Option<String>,
    pub current_period_type: Option<String>,
    pub current_period_start: Option<Date>,
    pub current_period_end: Option<Date>,
    pub current_fiscal_year_start: Option<Date>,
    pub current_fiscal_year_end: Option<Date>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sales: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub operating_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub ordinary_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub net_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub eps: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bps: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_assets: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub equity: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub equity_to_asset_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub roe: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash_flow_operating: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash_flow_investing: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash_flow_financing: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash_and_equivalents: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dividend_annual: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dividend_annual_forecast: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dividend_annual_forecast_next: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub forecast_sales: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub forecast_operating_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub forecast_ordinary_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub forecast_net_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub forecast_eps: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_forecast_sales: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_forecast_operating_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_forecast_ordinary_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_forecast_net_profit: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_forecast_eps: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
