//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "hypothesis_proposal")]
#[schema(as = HypothesisProposal)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hypothesis_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposed_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposed_body: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposed_status: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub rationale: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub review_note: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub reviewed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hypothesis::Entity",
        from = "Column::HypothesisId",
        to = "super::hypothesis::Column::HypothesisId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hypothesis,
}

impl Related<super::hypothesis::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hypothesis.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
