//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "indicator_observation")]
#[schema(as = IndicatorObservation)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub indicator_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    pub value: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::indicator::Entity",
        from = "Column::IndicatorId",
        to = "super::indicator::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Indicator,
}

impl Related<super::indicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Indicator.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
