//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "margin_alert")]
#[schema(as = MarginAlert)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pub_date: Date,
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub app_date: Date,
    #[sea_orm(column_type = "JsonBinary")]
    pub pub_reason: Json,
    pub shrt_out: i64,
    pub long_out: i64,
    pub shrt_out_chg: Option<i64>,
    pub long_out_chg: Option<i64>,
    pub shrt_out_ratio: Option<Decimal>,
    pub long_out_ratio: Option<Decimal>,
    pub sl_ratio: Option<Decimal>,
    pub shrt_neg_out: i64,
    pub shrt_std_out: i64,
    pub long_neg_out: i64,
    pub long_std_out: i64,
    pub tse_mrgn_reg_cls: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
