//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "news_strategy_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub news_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub strategy_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub ref_kind: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub ref_id: String,
    #[sea_orm(column_type = "Text")]
    pub matched_term: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::news_item::Entity",
        from = "Column::NewsId",
        to = "super::news_item::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NewsItem,
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::news_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsItem.def()
    }
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
