//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "note_version")]
#[schema(as = NoteVersion)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    pub note_id: Uuid,
    #[sea_orm(unique_key = "note_version_note_id_version_no_key")]
    pub version_no: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub body_md: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub frontmatter_json: Json,
    #[sea_orm(column_type = "JsonBinary")]
    #[schema(value_type = Vec<crate::services::graph::GraphDef>)]
    pub graphs_json: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub is_current: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub change_reason: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub created_by_kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub execution_id: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub reviewed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::note::Entity",
        from = "Column::NoteId",
        to = "super::note::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Note,
}

impl Related<super::note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Note.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
