//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "note_link")]
#[schema(as = NoteLink)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub from_version_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub to_note_id: Uuid,
    pub to_version_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::note::Entity",
        from = "Column::ToNoteId",
        to = "super::note::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Note,
    #[sea_orm(
        belongs_to = "super::note_version::Entity",
        from = "Column::FromVersionId",
        to = "super::note_version::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NoteVersion2,
    #[sea_orm(
        belongs_to = "super::note_version::Entity",
        from = "Column::ToVersionId",
        to = "super::note_version::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    NoteVersion1,
}

impl Related<super::note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Note.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
