//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ref_term")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ref_kind: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ref_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub term: String,
    pub origin: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
