//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "ref_term")]
#[schema(as = RefTerm)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ref_kind: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ref_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub term: String,
    pub origin: String,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
