//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "short_sale_report")]
#[schema(as = ShortSaleReport)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub disc_date: Date,
    #[sea_orm(primary_key, auto_increment = false)]
    pub calc_date: Date,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub code: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub ss_name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub ss_addr: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dic_name: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub dic_addr: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub fund_name: String,
    pub short_position_ratio: Decimal,
    pub short_position_shares: i64,
    pub short_position_units: i64,
    pub prev_report_date: Option<Date>,
    pub prev_report_ratio: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
