//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::StrategyTaskStepStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "strategy_task_step")]
#[schema(as = StrategyTaskStep)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub execution_step_id: Uuid,
    pub task_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub phase_key: String,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub model: String,
    pub status: StrategyTaskStepStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub item: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub item_label: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub output: Option<Json>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub started_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub trace_id: String,
    #[sea_orm(column_type = "Text")]
    pub span_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub seq: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::strategy_task::Entity",
        from = "Column::TaskId",
        to = "super::strategy_task::Column::TaskId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    StrategyTask,
}

impl Related<super::strategy_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
