//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::StrategyAgentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "strategy")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub agents_md: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub skills: Json,
    pub agent_status: StrategyAgentStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub agent_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(has_many = "super::note::Entity")]
    Note,
    #[sea_orm(has_many = "super::strategy_interest::Entity")]
    StrategyInterest,
    #[sea_orm(has_many = "super::strategy_task::Entity")]
    StrategyTask,
    #[sea_orm(has_many = "super::trade::Entity")]
    Trade,
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotation.def()
    }
}

impl Related<super::note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Note.def()
    }
}

impl Related<super::strategy_interest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyInterest.def()
    }
}

impl Related<super::strategy_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyTask.def()
    }
}

impl Related<super::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
