//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::StrategyTaskPhase;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "strategy_task")]
#[schema(as = StrategyTask)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: Uuid,
    pub strategy_id: Uuid,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub a2a_task_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub prompt: String,
    pub phase: StrategyTaskPhase,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_summary: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub result_text: Option<String>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub deadline_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary")]
    pub steps: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
