//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "strategy")]
#[schema(as = Strategy)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sort_order: i32,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub agents_md: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub skills: Json,
    #[sea_orm(column_type = "Text")]
    pub agent_graph: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::annotation::Entity")]
    Annotation,
    #[sea_orm(has_many = "super::custom_indicator::Entity")]
    CustomIndicator,
    #[sea_orm(has_many = "super::hypothesis::Entity")]
    Hypothesis,
    #[sea_orm(has_many = "super::news_strategy_link::Entity")]
    NewsStrategyLink,
    #[sea_orm(has_many = "super::note::Entity")]
    Note,
    #[sea_orm(has_many = "super::strategy_interest::Entity")]
    StrategyInterest,
    #[sea_orm(has_many = "super::strategy_task::Entity")]
    StrategyTask,
    #[sea_orm(has_many = "super::trade::Entity")]
    Trade,
    #[sea_orm(has_many = "super::trigger::Entity")]
    Trigger,
}

impl Related<super::annotation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Annotation.def()
    }
}

impl Related<super::custom_indicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomIndicator.def()
    }
}

impl Related<super::hypothesis::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hypothesis.def()
    }
}

impl Related<super::news_strategy_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewsStrategyLink.def()
    }
}

impl Related<super::note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Note.def()
    }
}

impl Related<super::strategy_interest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyInterest.def()
    }
}

impl Related<super::strategy_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategyTask.def()
    }
}

impl Related<super::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

impl Related<super::trigger::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trigger.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
