//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "strategy_task_step_evidence")]
#[schema(as = StrategyTaskStepEvidence)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub execution_step_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub source_ref: String,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub observed_at: DateTimeWithTimeZone,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub published_at: Option<DateTimeWithTimeZone>,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub effective_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary")]
    pub snapshot: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
