//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "trigger")]
#[schema(as = Trigger)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub trigger_id: Uuid,
    pub strategy_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub schedule: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub hook_slug: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub event_match: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub prompt_template: String,
    pub enabled: bool,
    #[schema(value_type = Option<chrono::DateTime<chrono::Utc>>)]
    pub last_fired_at: Option<DateTimeWithTimeZone>,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub created_at: DateTimeWithTimeZone,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::strategy::Entity",
        from = "Column::StrategyId",
        to = "super::strategy::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Strategy,
}

impl Related<super::strategy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategy.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
