//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "watchlists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub sort_order: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::watchlist_items::Entity")]
    WatchlistItems,
}

impl Related<super::watchlist_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WatchlistItems.def()
    }
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        super::watchlist_items::Relation::Instruments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::watchlist_items::Relation::Watchlists.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
