//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "watchlist_items")]
#[schema(as = WatchlistItem)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub watchlist_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub instrument_id: String,
    pub sort_order: i32,
    #[schema(value_type = chrono::DateTime<chrono::Utc>)]
    pub added_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::instruments::Entity",
        from = "Column::InstrumentId",
        to = "super::instruments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instruments,
    #[sea_orm(
        belongs_to = "super::watchlists::Entity",
        from = "Column::WatchlistId",
        to = "super::watchlists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Watchlists,
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instruments.def()
    }
}

impl Related<super::watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Watchlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
