[package]
name = "core-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
jpholiday = { workspace = true }
rust_decimal = { workspace = true, features = ["serde-float", "serde-arbitrary-precision"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
