[package]
name = "gateway-litellm"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
core-application = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
indoc = "=2.0.7"
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = { workspace = true }

[lints]
workspace = true
