[package]
name = "entrypoint-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true, features = ["clock"] }
core-application = { workspace = true }
graphile_worker = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
core-application = { workspace = true, features = ["test-support"] }
core-domain = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }

[lints]
workspace = true
